version: "3.8"

services:
  app:
    image: paxprz/useritems:latest
    command: "python cli.py serve 0.0.0.0"
    ports:
      - 8080:8080
    working_dir: /app
    env_file:
      - docker.env
  
  db:
    image: postgres:13.3-alpine
    hostname: mypostgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: testdb
    volumes:
      - ./var/pgdata:/var/lib/postgresql/data
    ports:
      - 5433:5432
